[DOCUMENTATION]
ORG_NAME="mymistech Inc."
ORG_URL="http://tzwl.store"
ORG_DESCRIPTION="trillion Zimbabwe dollars concept token"

[[CURRENCIES]]
code="tZWL"
issuer="GCSMNSIAJ7DM2BAMH4VHA5F3CQBHQCZWZX53J22OQZAHCLZDTO6IJIXF"
display_decimals=4 
image="https://mymistech.github.io/tzwl/tZWL.png"
name="tZimbabweDollars"
desc="trillion Zimbabwe dollars concept token"
fixed_number = 1000000000
conditions="hot"
status="live"
